# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool: myubuntuagent


variables:
  phpVersion: 8.1

steps:

- script: composer install --ignore-platform-reqs
  displayName: 'composer install'
